rate_limit: 5
logging: 'INFO'
caltopo_url: 'https://caltopo.com/api/v1/position/report/<your_key_here>'
filter: "type mgt subtype action"
#database: 'archive.db'
ignore:
  - "<your_uas_id_here>"

# if set, only the following UAS IDs will be monitored
#allow:
#  - "<your_uas_id_here>"
